### ISSUE TITLE
V2 documentation logistics

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api-v2#101]
The WG will flesh out some plans for V2 document migration. There are a couple of issues, but the general consensus is to separate out the V2 spec. 

## Proposal
* When adding a complete new feature, it can go directly to V2.
* When adding improvements on an existing feature, we can copy V1 text over to V2 and make some modifications.

* Good-first-issues:
  * NoiseGenerator (a brand new spec): [issue](https://github.com/WebAudio/web-audio-api-v2/issues/8
)
  * AudioParam power law (improvements): [issue](https://github.com/WebAudio/web-audio-api-v2/issues/22)

**Comment by rtoy** [comment]
I think with the decision to make V1 a living spec, we don't need to do anything here.  That really simplifies things.

**Comment by padenot** [comment]
Yes.
