### ISSUE TITLE
AnalyserNode: provide access to complex FFT result

### ISSUE THREAD

**Issue by linolinco** [WebAudio/web-audio-api-v2#107]
AnalyserNode already performs a windowed FFT. However, it provides only access to a smoothed power spectrum (log-magnitudes of the complex FFT result vector) through getFloatFrequencyData() resp. getByteFrequencyData(). There is no access to raw magnitude nor any phase information, even though the FFT must compute it. This needlessly limits the applicability of AnalyserNode.

Please add an accessor getComplexFrequencyData() that returns the unsmoothed complex-valued FFT result vector (called X[k] [here](https://webaudio.github.io/web-audio-api/#fft-windowing-and-smoothing-over-time) directly. Whatever format is used internally is fine - it could be a float[2][fftsize], float[fftsize][2], or float[2*fftsize] with real and imaginary components interleaved or not. The idea here is to provide direct access to the FFT result without incurring any performance penalties.

A getPolarFrequencyData() that converts the FFT result into polar (magnitude & phase) coordinates would also be useful, as this is a frequent use case. Alternatively, since the existing getFloatFequencyData() infrastructure (with smoothing, log, and scaling) already provides the magnitudes, a getPhaseData() that computes just the phase vector would suffice. [Here](https://www.dsprelated.com/showarticle/1052.php) is a fast atan2() approximation that would provide added value. Cheers!

**Comment by rtoy** [comment]
Perhaps with symmetry with `BiquadFilterNode.getFrequeqncyResponse`, the `AnalyyserNode` could have something similar return the magnitude and phase (arg) of the FFT.

I think if you want no smoothing, just set `smoothingTimeConstant` to zero.

**Comment by linolinco** [comment]
I believe 'arg' is identical to what I called 'atan2'.

Yes, `AnalyserNode.getPolarFrequencyData` could look quite similar to `BiquadFilterNode.getFrequencyResponse`. I'd return the *squared* magnitudes here though - sqrt() is a relatively expensive operation, and easy enough for the user to apply herself if needed (just like log, if that is desired).

There should still be an accessor for the raw (rectangular complex) FFT result though, since that carries zero post-processing cost and can then be used by anyone to implement whatever post-processing they desire. 

Setting `smoothingTimeConstant` to zero still gets you log-magnitudes in dB; if you need the raw magnitudes you'll have to re-exponentiate, which is expensive. This is exactly why access to the raw FFT result with _no post-processing whatsoever_ is needed: everything else, including the existing frequency-domain API, applies post-processing that is specific to particular use cases.

**Comment by rtoy** [comment]
Yes `arg` is `atan2`

**Comment by rtoy** [comment]
Teleconf:  While we could provide this access, we think it's not actually going to work the way people want.  Since the request for the data is on the main thread and the data is on the audio thread, you don't really know what you're getting.  The thread hop introduces some unknown delay.  For example, if you have an FFT size of 2048 frames, it's not really possible to request an FFT so that you get exactly 2048 non-overlapping non-skipping samples.  You may get a few frames that were calculated from last time, or you might have completely skipped some frames.  It's hard to know.

For the kind of analysis we think people do with the FFTs, uncontrolled skipping or overlapping like this does not work.  It needs to be done in a ScirptProcessor or AudioWorklet with your own FFT so that you get all the data exactly when you need it.

We suggest perhaps using [PFFFT](https://bitbucket.org/jpommier/pffft/src/master/)  compiled to WASM.  (Chrome uses PFFFT internally, except on Mac.)

**Comment by linolinco** [comment]
I see. Yes, uncontrolled skipping or overlapping would indeed render the phase information all but useless. The only way it could be made tolerable would be through exact bookkeeping - if I knew precisely where in the audio stream the window I'm getting is located, I could compensate for skips & overlaps. It would still be a pain though, and with `AudioWorklet/Processor` there's a better solution for this.

The only concern I have about `AudioWorklet/Processor` is that Safari still does not seem to support it. Do you happen to have any visibility on whether/when that might change? Myself I couldn't care less, but there's a significant percentage of hardcore iOS fans among my users...

I now also understand the dynamics of the old discussions about this topic on the v1 thread better - the thread hop issue was the elephant in the room, assumed but never mentioned by all those familiar with WebAudio's architecture. This explains the "of course you'll have to implement your own FFT" attitude that triggered me... may I suggest putting a note in the API docs for `AnalyserNode` explaining this limitation and steering people towards `AudioWorklet/Processor` for any work that can't tolerate it? This would prevent newcomers like me that are looking for the place to hook their own processing into WebAudio from thinking `AnalyserNode` is what they want, getting frustrated the same way I did.

Thanks for your forebearance, and for looking into this! And also for the PFFFT pointer, that looks very promising. I've been using the [Ooura](http://www.kurims.kyoto-u.ac.jp/~ooura/fft.html) package which is also narrow in scope, single C file, free license, has thread support but no SIMD acceleration. And it hasn't been updated in 14 years now, so I'm looking forward to trying a fresher horse! Cheers

**Comment by rtoy** [comment]
You'll be pleased to hear that Safari recently landed support for AudioWorklets.  Don't know when that will show up, but it's in the pre-release and tested at https://wpt.fyi/webaudio.  This was a long awaited and very, very welcome update for the WebAudio community!

Since we're trying hard to finish up V1, I doubt we'll add additional text for the AnalyserNode.  Perhaps for the next version.

PFFFT is pretty old too (coming from the 1985 fftpackv4). I hope it works well for you.  I've never tried using compiling for wasm, though.  Good luck!

**Comment by rtoy** [comment]
Oops.  I thought this was filed for v1, but it's actually v2.  So, yeah, we can consider adding an informative note about this.

**Comment by linolinco** [comment]
That's very good news about Safari - means I can in good conscience invest significant effort in shifting to WebAudio as future main platform. Since Apple has everyone in a tight upgrade hamster wheel take-up won't take too long, once they do release it.

Regarding PFFFT's age: well fortunately the FFT math hasn't changed since the 50s, and PFFFT does add SIMD support over fftpack. I also tend to look at the last significant commit as an indicator of software health, and that was 4 years ago for PFFFT (adding 64-bit arm support, relevant to me) vs. 19 years ago for Ooura (adding thread support, not relevant to me). So that new horse definitely looks younger! :)

If there's interest, I can report back here how compiling PFFFT to WASM is working out.

Thanks again, you've been super helpful! 👍

**Comment by rtoy** [comment]
I think you'd do a great service to the community if you did create a nice PFFFT WASM implementation that anyone can use.  

Good luck!

**Comment by rtoy** [comment]
Teleconf (Dec 10) comments:
As mentioned, for the kind of analysis being asked here, the `AnalyserNode` won't work. You will have to use a `ScriptProcessorNode` or `AudioWorkletNode` to do the desired analysis with your own FFT.

**Comment by linolinco** [comment]
I've explored the `AudioWorkletNode` route now but ran into a serious problem: the only documented way to get analysis results from the audio worklet to the UI thread appears to be by posting messages, and this slows the system to an unusable crawl. 

Basically, I have some visual properties in CSS/DOM that I want to animate in real time based on the results of my audio analysis. When I feed the visual animation with dummy values, it runs happily at 60fps. My `AudioWorkletProcessor` (with WASM-based FFT) runs happily. Both run happily at the same time, not taxing the CPU by any means. But as soon as I try to message results 43 times a second from one to the other, the messages pile up into an ever-growing backlog. The messaging system appears to be rather inefficient and does not seem to support any higher throughput than a couple of messages per second?

So as it looks to me now, the prototypical processing pipeline of any real-time audio analysis system (audio in -> FFT -> analysis -> visual animation) cannot be implemented in WebAudio by any of the available means?
1. `AnalyserNode` is not suitable per our above discussion
2. `ScriptProcessorNode` is deprecated, may be dropped at any time
3. `AudioWorkletNode` has no efficient means to get data from `AudioWorkletProcessor`?

Or am I missing something - is there some more efficient way to send messages? Or some other way to get data from the audio to the UI thread? Can I perhaps set `AudioParam`s in the `AudioWorkletProcessor` and read them back in `AudioWorkletNode`?

Apologies for airing my difficulties here, but I do feel my use case -- and thus the problems I'm running into here -- to be  typical and representative of a very broad class of audio analysis software. To the extent that WebAudio wants to support such use cases (and I think it should!), my case might serve to identify the remaining roadblocks here.

It might even be just a documentation issue... if I were writing an audio *synthesizer* I could literally start with the examples in the WebAudio API docs at MDN, flesh them out a little and bingo. But I can't find any example at all of the reverse process, getting analysis data back from an audio worklet. I cannot tell whether this is because no efficient method exists, or whether it just isn't documented.

**Comment by linolinco** [comment]
By the way, I've added WASM-SIMD support to PFFFT as we discussed. Would be happy to contribute it, but Julien Pommier's original code on bitbucket seems to be abandoned (there's an unanswered one-line pull request from 2015). There are several github forks of it, but I do not know their status; would prefer to contribute to the canonical source.

Since browser support of WASM-SIMD is still razor-thin I've switched back to Ooura's FFT code for now, which (albeit more limited) is slightly faster than PFFFT without SIMD. Cheers

**Comment by rtoy** [comment]
I personally would not want `ScriptProcessorNode` to go away, but it might.  It's not up to me.

Yes, posting messages is very slow.  I think the right way is to use a `SharedArrayBuffer` to send your data.  I think there are several examples of this usage, but here's one: https://github.com/GoogleChromeLabs/web-audio-samples/tree/master/audio-worklet/design-pattern/shared-buffer/. Perhaps that will work for you.

About PFFFT, I've never talked to Julien Pommier, so I don't know the status.  If it were me, I'd make a fork, hack on it, and make pull requests.  If they're accepted, great!  If not, your fork could become the new canonical source if you're actively developing it.

**Comment by linolinco** [comment]
Thanks for the tips! Unfortunately `SharedArrayBuffer` has been disabled in most contexts because of Spectre, so it isn't a viable approach for me at this point. This might improve once other Spectre mitigation measures are ubiquitous. 

But in fact I've managed to solve the performance issue with `postMessage` - turns out it wastes a *huge* amount of time serializing/deserializing the data. There's a way to avoid that overhead by posting `Transferable` objects instead, such as an `ArrayBuffer`. Unlike `SharedArrayBuffer` this requires copying the data, but that's still far faster than serializing it. Haven't explored the limits of this approach yet, but my requirements (0.5kB of data 43 times a second) appear well within them.

For the benefit of others googling this, here's my resulting skeleton JS wrapper for a WASM-based  `AudioWorkletProcessor`:

```
        registerProcessor('example', class extends AudioWorkletProcessor {
            constructor (...args) {
                super(...args);
                this.buff = _malloc(512) >> 2;  // WASM heap space for an audio frame
            };

            process(inputs, outputs, parameters) {
                HEAPF32.set(inputs[0][0], this.buff);   // copy audio frame to WASM heap

                // call WASM routine to process the frame, replacing it with result data:
                _process(this.buff << 2);

                // create a new ArrayBuffer with a copy of the results:
                const msg = new Float32Array(HEAPF32.subarray(this.buff, this.buff + 128));

                // TRANSFER it (do NOT serialize) to AudioWorkletNode, losing ownership of msg
                this.port.postMessage(msg, this.port.origin, [msg]);
                return true;
            };
        });
```

**Comment by padenot** [comment]
AudioWG virtual f2f:
- Closing this for the reasons outlined in this thread
- We're optimizing the `AudioWorkletProcessor` so that copies from/to the WASM heap won't be as important in the future, and `SharedArrayBuffer` is generally been re-enabled everywhere now I think
