### ISSUE TITLE
AnalyserNode: efficiency improvements to FFT post-processing

### ISSUE THREAD

**Issue by linolinco** [WebAudio/web-audio-api-v2#108]
[https://webaudio.github.io/web-audio-api/#fft-windowing-and-smoothing-over-time](url) specifies the post-processing of the complex FFT result vector to obtain smoothed log-magnitudes for getFloatFrequencyData() in AnalyserNode. I want to suggest an efficiency improvement here.

Leaving out smoothing for the moment, the post-processing computes each element of the result vector as `Y[k] = 20*log10(sqrt(r[k]*r[k] + i[k]*i[k]))`, where r[k] and i[k] are the real and imaginary components of the complex FFT result X[k]. However, the sqrt() operation here can be eliminated, since `Y[k] = 10*log10(r[k]*r[k] + i[k]*i[k])` is mathematically identical.

Smoothing complicates this picture, since the two forms (with and without square root) are now no longer identical. Taking a step back, however, we can ask *why* there is smoothing before taking logs - what does that achieve? I believe that the unstated purpose here is to create a peak detector: exponential smoothing before taking logs creates an impulse response with exponentially fast attack but slow linear decay to zero, both at a rate governed by the smoothing constant tau.

The proposed sqrt-free version would make this asymmetry more pronounced - essentially doubling the attack and halving the decay rate. We could improve backwards compatibility by internally substituting `tau := 2*tau - 1` to re-double the decay rate, at the cost of now having quadruple the previous attack rate.

If this sounds bad, there are three mitigating factors at work here:
1. The slow decay is far more visible than the fast attack, so users use tau primarily to control the decay rate, which will remain the same.
2. Arguably most users want an instantaneous attack - a true peak detector. If they notice the quadrupled attack rate at all, they're more likely than not to be happy about it.
3. In the rare cases where a faster attack is not welcome, it is always possible to compensate by introducing additional smoothing *after* the log, i.e., on the user side.

Finally, I can provide a fast approximate log if there's interest. Cheers!

**Comment by rtoy** [comment]
I do not know the history of why things are computed the way they are, but  I suspect the original purpose of the AnalyserNode was primarily for visualization, not really analysis of the audio data.  If I were doing this, I'd at least have smoothing done based on [Bartlett's method of averaged periodograms.](https://en.wikipedia.org/wiki/Bartlett%27s_method)

I think it's too late to change the algorithms unless it gives something truly and significantly better in some way.

**Comment by linolinco** [comment]
I totally agree with your assessment. I just wanted to write down the result of my looking into it here for reference, in case someone does decide to overhaul AnalyserNode at some point, or create a better replacement for it. I can understand if there is no urgent motivation to do this though. My parallel feature request (to get access to the raw FFT output) will provide a workaround for anyone who wants to use AnalyserNode's FFT but is unhappy with its prepackaged postprocessing.

Interestingly, Bartlett's method also smoothes the *squared* magnitude, same as I proposed. For a stream-oriented framework, I think replacing an average with an exponential running average as done here for smoothing is a reasonable modification.

**Comment by rtoy** [comment]
Teleconf:  We have no plans on changing the algorithm for the AnalyserNode; it's too late for that.

Closing.
