### ISSUE TITLE
Set up to display the spec.

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api-v2#114]
**Describe the Issue**
Need to setup github/travis to display the spec.  Currently there's nothing.

**Expected Result**
https://webaudio.github.io/web-audio-api-v2 should display the v2 version of the spec (that currently has no new content).

**Actual Result**
404

**Comment by rtoy** [comment]
Also need Travis CI to be setup, along with github pages(?) for this to work like what we have for v1.

**Comment by rtoy** [comment]
Travis CI and PR Preview just needed to be updated by going to the WebAudio/web-audio-api, opening Settings>Integrations and then configuring PR Review and Travis CI apps to add the v2 repo to the list of repos that have access.

**Comment by rtoy** [comment]
Also needed to set up gh-pages. Goto Settings and scroll down to Github pages and set the source branch to gh-pages. (I created the gh-pages branch just before this.)  It should now say that site will be published to https://webaudio.github.io/web-audio-api-v2/.

(Still currently untested.)

**Comment by rtoy** [comment]
I think I have everything needed to deploy the spec.  However, Travis is failing.  I'm assuming it can't get the deploy token.

Can you help out with that @padenot?  From the logs on v1, you implemented the new deploy method.  (Side note, some documentation on how to do this would be useful for current and future users.)

**Comment by rtoy** [comment]
This still needs work.  The current draft spec isn't displayed, even though Travis CI is working and the preview/diff is also working.

**Comment by rtoy** [comment]
This is no longer relevant now that we've decided to make the spec a living document.

**Comment by dontcallmedom** [comment]
can you clarify the impact of making the spec a living document? Where one would find the latest view of the what the group is doing with WebAudio ?

**Comment by rtoy** [comment]
I think @svgeesus can provide more details, but my understanding is that we'll keep updating the editor's draft which will have all of the candidate corrections and additions.  At some appropriate point, the changes will get incorporated in a new recommendation, and we'll start all over with new corrections and additions.

**Comment by dontcallmedom** [comment]
to be clear, by editors draft you mean https://webaudio.github.io/web-audio-api/ ? is there any clarity about what needs to go (e.g. issues) to https://github.com/WebAudio/web-audio-api-v2 vs https://github.com/WebAudio/web-audio-api ? It would be good to document this on the relevant repo READMEs

**Comment by rtoy** [comment]
Yes, that's the draft that we'll maintain.  We're still not sure what to do about the issues.  I think the consensus was to move the v2 issues back to v1 and basically get rid of the v2 repo.  We just haven't done that yet.  We'll update the READMEs once we do this.
