### ISSUE TITLE
Switching between 2 Microphones 

### ISSUE THREAD

**Issue by MariaPapadaki** [WebAudio/web-audio-api-v2#128]
I am developing a 3D environment that connects two microphones with a specific geometry in my scene , runs locally for now.
I want to be able to switch between which microphone is being used ( when I press key A  use mic1 and when I press key B use mic 2 ).
The error I get is : 
 Firefox ----> Error:NotReadableError: Concurrent mic process limit.
Chrome ->  no Error, it just doesn't switch devices

How can I fix that ? I tried to stop the stream but it doesn't work , any suggestions ?

**Comment by rtoy** [comment]
This issue tracker is for issues in the spec, not general WebAudio usage questions.

If you need help on how to use WebAudio, ask on your favorite forum or consider visiting the [WebAudio Slack Channel](https://web-audio.slack.com/) (register [here](https://web-audio-slackin.herokuapp.com/)) or [StackOverflow](https://stackoverflow.com/).

If this is really an issue with the spec, please re-open or file a new issue.
