### ISSUE TITLE
Permit loading of custom HRTFs (including SOFA)

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api-v2#17]
Christian Hoene:

> in order to support high quality spatial audio rendering, individualized HRTF should be used.
> 
> Recently, the AES has standardized the SOFA format, which describes HRTFs.
> 
> So far, each browser just uses a default HRTF. I am wondering, whether Web Audio should support the SOFA format and thus individualized HRTFs.
> 
> Any plans?

**Comment by rtoy** [comment]
To be handled in #21
