### ISSUE TITLE
Handling of output parameter for worklet process()?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api-v2#42]
Let's say you have a very simple `AudioWorklet` having a single input and a single output with no `AudioParams`.  Let's say you made a mistake and have

```
process(inputs, outputs, params) {
  let input = inputs[0];
  let output = outputs[0];
  output.fill(input[0][0]);
  return true;
}
```
This accidentally modifies `outputs[0]` to be an array of floats.  But it's supposed to be a `sequence<Float32Array>`.

How is the worklet supposed to handle this?  I'm kind of thinking this should cause an error to be thrown.  I guess that also implies that if `output` isn't exactly `sequence<sequence<Float32Array>>` an error is thrown.  Similarly, if the length of the `Float32Array` isn't 128, it's an error.

(In case it matters, I actually did this by accident.)

**Comment by padenot** [comment]
F2F summary:

- This is important
- Not talked about at length during the f2f because key people were missing from the discussion
- The arrays are `FrozenArray` now
- This also ties into https://github.com/WebAudio/web-audio-api-v2/issues/4

**Comment by rtoy** [comment]
I think we should close this issue since the original question in https://github.com/WebAudio/web-audio-api-v2/issues/42#issue-494451819 can't happen anymore since the arrays are now Frozen.  Anything else that needs to be done can be handled in #37, which is where lots of the comments here were headed anyway.

**Comment by rtoy** [comment]
TPAC: Yes, modifications as mentioned in https://github.com/WebAudio/web-audio-api-v2/issues/42#issue-494451819 can't happen anymore.  Closing this.  Changes will be handled in #37.
