### ISSUE TITLE
Allow OfflineAudioContext to render smaller chunks repeatedly

### ISSUE THREAD

**Issue by JohnWeisz** [WebAudio/web-audio-api-v2#6]
Unless I'm mistaken, it seems the Web Audio API spec does not define a standard way to manually terminate an OfflineAudioContext.

The closest we have is calling `suspend` on an already running OfflineAudioContext, which does not dispose the context however, and will accumulate used memory. `close` is specced only to AudioContext (not AudioContextBase or OfflineAudioContext), so we can't use that here.

Shouldn't closing be possible on OfflineAudioContext as well?

### Use case

Our use case is a DAW that supports hour long compositions causing an `OfflineAudioContext.startRendering` call to sometimes take up an entire hour, and it would be nice to offer users a way to cancel the process.

The only workaround I know about at this time is `window.location.reload()`, and thus perhaps running the rendering process in an `iframe`, which can be reloaded without reloading my entire app.

**Comment by rtoy** [comment]
See also #66

**Comment by rtoy** [comment]
Closing  this.  #66 should be able to handle early termination since we're incrementally delivering audio.  Just need to add some kind of `close` method to indicate that the offline context is done.
