### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api-v2#60]
**Describe the Issue**
See WebAudio/web-audio-api#2106 for a PR to add a pull request template.  We're not going to do that for v1, but we will for v2, as mentioned in https://github.com/WebAudio/web-audio-api/pull/2106#issuecomment-565109608

This is a reminder for us to take that merge request and move it/duplicate it to this repo.

**Comment by svgeesus** [comment]
https://github.com/WebAudio/web-audio-api-v2/pull/86

**Comment by padenot** [comment]
Closed by #86.
