### ISSUE TITLE
Enforcing range of unsigned long attributes

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api-v2#65]
**Describe the feature**
For example, the constructor for `OfflineAudioContext` takes an `unsigned long` for the `length` parameter.  This means the actual length is the given length modulo `2^32`, according to https://heycam.github.io/webidl/#abstract-opdef-converttoint

It might be useful if we added the [`[EnforceRange]` attribute](https://heycam.github.io/webidl/#EnforceRange) to cause an error to be thrown when the parameter is outside the range.

If this makes sense, we should probably apply this everywhere we use `unsigned long`.

It's certainly easier to understand if we get an error when we ask for an `OfflineAudioContext` of length 4294967297 and end up with no errors and a context with length 1.

**Comment by rtoy** [comment]
Oh, this would, of course, break backward compatibility.  I'm expecting no one is actually using the modulo feature.

**Comment by padenot** [comment]
Telcon decision: in practice, the length of OfflineAudioContext are gated on Float32Array max length, so this is not so much a backwards compatibility risk.

In general, similarly, there are other checks that happen already for values much less than the limit of the number, so it's not much of a compat risk. For example, the number of channels is usually limited to a double digit number.

The wrapping however is annoying, and [EnforeRange] help there.

We'll implement this.

**Comment by padenot** [comment]
Virtual F2F:
- Do this for new APIs

**Comment by hoch** [comment]
I don't see any "EnforceRange" in the IDL. What is done and what else is left for this issue?

**Comment by rtoy** [comment]
As mentioned in https://github.com/WebAudio/web-audio-api-v2/issues/65#issuecomment-644846623 we'll only do this for new APIs.  But https://github.com/WebAudio/web-audio-api-v2/issues/65#issuecomment-585880606 kind of contradicts this.  Need to dig through the meeting minutes to see if there's additional detail.

But I certainly would like things like the length of an OfflineAudioContext to be enforced instead of wrapping around.
