### ISSUE TITLE
Remove compileStreaming and instantiateStreaming from AudioWorkletGlobalScope.WebAssembly implementation

### ISSUE THREAD

**Issue by guest271314** [WebAudio/web-audio-api-v2#79]
**Describe the issue**
```
console.log('compileStreaming' in globalThis.WebAssembly);
console.log('instantiateStreaming' in globalThis.WebAssembly);
```

both return `true` at Nightly 78 and Chromium 81. 

However, those methods cannot be used in `AudioWorkletGlobalScope` without throwing a `TypeError` because `Response` is not defined in `AudioWorkletGlobalScope`

https://webassembly.org/docs/web/#process-a-potential-webassembly-response

> **Process a potential WebAssembly response**
> The above two functions both reuse much of the same infrastructure for extracting bytes from an appropriate [`Response`](https://fetch.spec.whatwg.org/#response-class) object, differing only in what they do with those bytes in the end. As such we define the following shared spec-level procedure:
> 
> ...
> 
> Given these values, to process a potential WebAssembly response:
> 
> 1.    Let _returnValue_ be [a new promise](https://www.w3.org/2001/tag/doc/promises-guide#a-new-promise).
> 2.  Let _sourceAsPromise_ be [a promise resolved with](https://www.w3.org/2001/tag/doc/promises-guide#a-promise-resolved-with) argument.
> 3. [Upon fulfillment](https://www.w3.org/2001/tag/doc/promises-guide#upon-fulfillment) of `sourceAsPromise` with value `unwrappedSource`:
> i. If unwrappedSource is not a [`Response`](https://fetch.spec.whatwg.org/#response-class) object, [reject](https://www.w3.org/2001/tag/doc/promises-guide#reject-promise) _returnValue_ with a `TypeError` exception and abort these substeps.

Specification authors object to defining `fetch()`, thus `Response`, in `AudioWorkletGlobalScope` where the methods now are only capable of throwing a `TypeError` per the `WebAsssembly` specification, thus should be removed from `AudioWorkletGlobalScope.WebAssembly` implementation.

**Where Is It**

> **[1.32.1. Concepts](https://webaudio.github.io/web-audio-api/#AudioWorklet-concepts)**
> 
> The [`AudioWorklet`](https://webaudio.github.io/web-audio-api/#audioworklet) object allows developers to supply scripts (such as JavaScript or WebAssembly code) to process audio on the [rendering thread](https://webaudio.github.io/web-audio-api/#rendering-thread), supporting custom [`AudioNode`](https://webaudio.github.io/web-audio-api/#audionode)s. This processing mechanism ensures synchronous execution of the script code with other built-in [`AudioNode`](https://webaudio.github.io/web-audio-api/#audionode)s in the audio graph.

https://webassembly.org/docs/web/#additional-web-embedding-api

> **Additional Web Embedding API**
> 
> In Web embeddings, the following methods are added.
> 
> Note that it is expected that `compileStreaming` and `instantiateStreaming` be either both present or both absent.

**Additional Information**

Where specification authors appear to be in firm agreement to _not_ define `fetch()`,  and thus `Response`, in `AudioWorkletGlobalScope` https://github.com/WebAudio/web-audio-api-v2/issues/73, where if that decision remains unchanged `compileStreaming()` and `instantiateStreaming()` will always _only_ throw a `TypeError` rendering the methods useless in `AudioWorkletGlobalScope`.

The `WebAssembly` specification provides the solution to the bug "both absent" must apply in this case.

If the specification authors conclude that a `TypeError` being thrown for `WebAssembly.compileStreaming()` and `WebAssembly.instantiateStreaming()` which is the only possible outcome due to `Response` not being defined in `AudioWorkletGlobalScope` at a minimum a note should be included in the specification to notify users that while `compileStreaming()` and `instantiateStreaming()` are defined methods within `AudioWorkletGlobalScope` using either will only result in a `TypeError` being thrown as `Response` is not defined in the `AudioWorkletGlobalScope`.

**Comment by padenot** [comment]
Virtual F2F:
- https://webassembly.org/docs/web/ hints at the fact that it might be possible to not expose those in some context, but only makes the Web/Not Web distinction

**Comment by guest271314** [comment]
@padenot Or, expose `Response` and `fetch` in `Worklet`/`AudioWorkletGlocalScope`. Hundreds of thousands to millions of `MessagePort` events and message events is more than likely more expensive than just fetching the input data in `AudioWorkletGlobalScope`. The design pattern appears to have neglected to consider how to get substantial amounts (potentially an infinite stream) of input data data to `AudioWorkletProcessor`. 

If `Response` and `fetch` cannot be  defined in `AudioWorkletGlobalScope` every effort should be made to concretely implement transferable streams to replace the expensive `MessagePort` implementation. Though we should be able to compare `fetch` and `Response` in `AudioWorkletGlobalScope` to using `WebAssembly`, `Atomics` and `SharedArrayBuffer` to base conclusions about performance on evidence rather than assumptions.

**Comment by padenot** [comment]
TPAC 2020:
- @hoch will ask around and find out whether it's possible to _not_ expose those in a particular context.

**Comment by guest271314** [comment]
Another option is to expose `Response` in `AudioWorkletGlobalScope`. Then `blob()` and `formData()` would need the same non-exposure becaude `Blob` is not defined in that context either. After thousands of experimental runs I do not have any evidence to support the propostion that `Response` or `fetch()` in `AudioWorklet` will break the API.

**Comment by hoch** [comment]
The streaming version already excludes the WGS:
https://webassembly.github.io/spec/web-api/index.html#streaming-modules

**Comment by hoch** [comment]
Nothing actionable here in terms of the spec change - the spec seems sufficient, but the implementations do not reflect it correctly. I filed an issue against Chromium: https://crbug.com/1144249

**Comment by padenot** [comment]
Gecko bug to remove those: https://bugzilla.mozilla.org/show_bug.cgi?id=1711945. I'm closing this, since both implementations are wrong.
