### ISSUE TITLE
OfflineAudioContext without a rendered buffer

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api-v2#82]
**Describe the feature**
It would be nice if the `OfflineAudioContext` could be configured to not allocate any memory for the rendered AudioBuffer in case it is not needed.

**Is there a prototype?**
No.

**Describe the feature in more detail**
Sometimes an `OfflineAudioContext` is only used to compute a side effect and not really for rendering a buffer.

Let's imagine you have an `AudioWorkletNode` which just scans the signal for its maximum value. Its usage might look like this:

```js
const offlineAudioContext = new OfflineAudioContext({ length: 44100, sampleRate: 44100 });
const audioBufferSourceNode = new AudioBufferSourceNode(
    offlineAudioContext,
    { buffer: aBufferFromSomewhere }
);
// This could be an AudioWorkletNode which scans the signal for its maximum value. 
const maximumValueNode = new MaximumValueNode(offlineAudioContext);

audioBufferSourceNode.start(0);
audioBufferSourceNode
    .connect(maximumValueNode)
    .connect(offlineAudioContext.destination);

offlineAudioContext
    .startRendering()
    .then(() => {
        // Now that the rendering is done ask the MaximumValueNode for the maximum value.
        console.log(maximumValueNode.maximumValue);
    });
```

In the example above the `OfflineAudioContext` is only used to drive the processing of the data but the rendered buffer is not really needed. I think it would be beneficial if the buffer doesn't need to be created in any case.

**Comment by guest271314** [comment]
In this case an `AudioBuffer` does not necessarily need to be created at all https://github.com/guest271314/audioInputToWav/blob/master/index.html#L345. The equivalent of an `AudioBuffer` can be an `Array` where `Array.prototype.find()` and `Math.max()` can be utilized to get the maximum value of a float.

**Comment by padenot** [comment]
Virtual F2F:
- There is going to be a way to have progressive rendering of `OfflineAudioContext` (talked about in #66 but also other issues), at which point the allocation will not be made (and will have to be made by the authors themselves, if needed). This problem then disappears.
