### ISSUE TITLE
Add frequency of one oscillator to be based on another

### ISSUE THREAD

**Issue by OscarDev** [WebAudio/web-audio-api-v2#93]
**Describe the feature**
Take two oscillators. Say I have one oscillatorA that is ramping linearly, I'd like there to be a way such that you can make the other oscillatorB scale as a function of the initial one.

For example:
`        oscNodeA.frequency.setValueAtTime(1, context.currentTime);
          oscNodeA.frequency.linearRampToValueAtTime(
            3000,
            context.currentTime + 10
          );
          oscNodeB.frequency.value = oscNodeA.frequency.value * 2;
`

Which should operate like if I pass oscNodeA.frequency.value in an object, it will constantly update the frequency as oscNodeA changes frequency. It's useful for shifting frequencies of whole chords made by Oscillators

**Comment by rtoy** [comment]
This issue tracker is for issues with the spec, not a general support tracker.

You should ask on the [WebAudio Slack Channel](https://web-audio.slack.com/) (register [here](https://web-audio-slackin.herokuapp.com/)) or
[StackOverflow](https://stackoverflow.com/)

Perhaps look into the [connect method](https://www.w3.org/TR/webaudio/#dom-audionode-connect-destinationparam-output) to connect the output of node a to the input to oscNodeB.frequency.
